services:
  automation:
    build:
        context: ..
        dockerfile: docker/automation
    volumes:
      - /Users/jc02788/Documents/accessibility_extensions:/src  # Mount the host directory
    entrypoint: /bin/bash  # Override default entrypoint
    tty: true  # Allocate pseudo-TTY (same as -it)
    networks:
        - automation-net

  web_server:
    build:
        context: ..
        dockerfile: docker/web_server
    ports:
        - "80:80"
    networks:
        - automation-net

networks:
    automation-net: {}
