services:
  automation:
    build:
        context: ..
        dockerfile: docker/automation
    volumes:
      - /Users/jc02788/Documents/accessibility_extensions:/src  # Mount the host directory
    entrypoint: /bin/bash  # Override default entrypoint
    tty: true  # Allocate pseudo-TTY (same as -it)
    networks:
        - automation-net
    environment:
        http_proxy: "http://mitmproxy:8080"
        https_proxy: "http://mitmproxy:8080"

  web_server:
    build:
        context: ..
        dockerfile: docker/web_server
    ports:
        - "80:80"
    networks:
        - automation-net

  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
    networks:
        - automation-net
    command: ["mitmweb","--web-host", "0.0.0.0"]

networks:
    automation-net: {}
